export const ELEMENTS = {
    title_element_male: '#id_gender1',
    title_element_female: '#id_gender2',
    first_name: '#customer_firstname',
    last_name: '#customer_lastname',
    password: '#passwd',
    days_tab: '#days',
    months_tab: '#months',
    years_tab: '#years',
    news_letter_check_box: '#newsletter',
    special_offer_check_box: '#optin',
    address_first_name: '#firstname',
    address_last_name: '#lastname',
    company_name: '#company',
    main_address: '#address1',
    additional_address: '#address2',
    city: '#city',
    state: '#id_state',
    zip_code: '#postcode',
    country: '#id_country',
    additional_information: '#other',
    home_phone: '#phone',
    mobile_phone: '#phone_mobile',
    alias_mail: '#alias',
    register_button: '#submitAccount > span'
}